# Null Handling

In [40]:
import pandas as pd 
#import numpy as np

In [41]:
df = pd.read_csv(r"C:\Users\acer\Downloads\agriculture_data_with_nulls_duplicates.csv")

In [42]:
print(df)

   Farm_ID       Crop           State  Area_Acres  Yield_Ton_per_Acre  \
0        1       Rice      Tamil Nadu      1200.0                 2.5
1        2      Wheat          Punjab      1500.0                 3.2
2        3      Maize       Karnataka         NaN                 2.8
3        4     Cotton         Gujarat      1800.0                 NaN
4        5  Sugarcane     Maharashtra      2000.0                 4.5
5        6       Rice      Tamil Nadu      1200.0                 2.5
6        7        NaN  Andhra Pradesh      1300.0                 2.9
7        8     Millet       Rajasthan      1100.0                 2.1
8        9  Groundnut      Tamil Nadu      1400.0                 3.0
9       10      Wheat          Punjab      1500.0                 3.2

  Harvest_Date  Farming_Type Irrigation  Income_INR
0   2026-01-10       Organic        Yes        5000
1   2026-01-11  Conventional         No        6200
2   2026-01-12       Organic        Yes        5400
3   2026-01-13  Conventional         No        7000
4          NaN       Organic        Yes        9000
5   2026-01-10       Organic        Yes        5000
6   2026-01-15       Organic        Yes        5600
7   2026-01-16           NaN         No        4800
8   2026-01-17       Organic        NaN        6100
9   2026-01-11  Conventional         No        6200

In [ ]:
# 1) Dropna    ---> remove entire rows having atleast one null

In [10]:
print(df.dropna())

   Farm_ID   Crop       State  Area_Acres  Yield_Ton_per_Acre Harvest_Date  \
0        1   Rice  Tamil Nadu      1200.0                 2.5   2026-01-10
1        2  Wheat      Punjab      1500.0                 3.2   2026-01-11
5        6   Rice  Tamil Nadu      1200.0                 2.5   2026-01-10
9       10  Wheat      Punjab      1500.0                 3.2   2026-01-11

   Farming_Type Irrigation  Income_INR
0       Organic        Yes        5000
1  Conventional         No        6200
5       Organic        Yes        5000
9  Conventional         No        6200

In [ ]:
# 2) dropna subset     ---> removes rows where name is null

In [11]:
print(df.dropna(subset=['Farming_Type']))

   Farm_ID       Crop           State  Area_Acres  Yield_Ton_per_Acre  \
0        1       Rice      Tamil Nadu      1200.0                 2.5
1        2      Wheat          Punjab      1500.0                 3.2
2        3      Maize       Karnataka         NaN                 2.8
3        4     Cotton         Gujarat      1800.0                 NaN
4        5  Sugarcane     Maharashtra      2000.0                 4.5
5        6       Rice      Tamil Nadu      1200.0                 2.5
6        7        NaN  Andhra Pradesh      1300.0                 2.9
8        9  Groundnut      Tamil Nadu      1400.0                 3.0
9       10      Wheat          Punjab      1500.0                 3.2

  Harvest_Date  Farming_Type Irrigation  Income_INR
0   2026-01-10       Organic        Yes        5000
1   2026-01-11  Conventional         No        6200
2   2026-01-12       Organic        Yes        5400
3   2026-01-13  Conventional         No        7000
4          NaN       Organic        Yes        9000
5   2026-01-10       Organic        Yes        5000
6   2026-01-15       Organic        Yes        5600
8   2026-01-17       Organic        NaN        6100
9   2026-01-11  Conventional         No        6200

In [ ]:
# 3) dropna how ='all'   ---> removes rows only when all columns are null

In [12]:
print(df.dropna(how ='all'))

   Farm_ID       Crop           State  Area_Acres  Yield_Ton_per_Acre  \
0        1       Rice      Tamil Nadu      1200.0                 2.5
1        2      Wheat          Punjab      1500.0                 3.2
2        3      Maize       Karnataka         NaN                 2.8
3        4     Cotton         Gujarat      1800.0                 NaN
4        5  Sugarcane     Maharashtra      2000.0                 4.5
5        6       Rice      Tamil Nadu      1200.0                 2.5
6        7        NaN  Andhra Pradesh      1300.0                 2.9
7        8     Millet       Rajasthan      1100.0                 2.1
8        9  Groundnut      Tamil Nadu      1400.0                 3.0
9       10      Wheat          Punjab      1500.0                 3.2

  Harvest_Date  Farming_Type Irrigation  Income_INR
0   2026-01-10       Organic        Yes        5000
1   2026-01-11  Conventional         No        6200
2   2026-01-12       Organic        Yes        5400
3   2026-01-13  Conventional         No        7000
4          NaN       Organic        Yes        9000
5   2026-01-10       Organic        Yes        5000
6   2026-01-15       Organic        Yes        5600
7   2026-01-16           NaN         No        4800
8   2026-01-17       Organic        NaN        6100
9   2026-01-11  Conventional         No        6200

In [ ]:
# 4) dropna axis = 1     --->  removes columns containing nulls

In [13]:
print(df.dropna(axis=1))

   Farm_ID           State  Income_INR
0        1      Tamil Nadu        5000
1        2          Punjab        6200
2        3       Karnataka        5400
3        4         Gujarat        7000
4        5     Maharashtra        9000
5        6      Tamil Nadu        5000
6        7  Andhra Pradesh        5600
7        8       Rajasthan        4800
8        9      Tamil Nadu        6100
9       10          Punjab        6200

In [ ]:
# 5)  fillna constant          ---> replaces nulls with constant value

In [14]:
print(df['Farming_Type'].fillna('unknown'))

0         Organic
1    Conventional
2         Organic
3    Conventional
4         Organic
5         Organic
6         Organic
7         unknown
8         Organic
9    Conventional
Name: Farming_Type, dtype: str

In [ ]:
# 6) fillna mean               ---> numerial imputation

In [15]:
print(df['Area_Acres'].fillna(df['Area_Acres'].mean()))

0    1200.000000
1    1500.000000
2    1444.444444
3    1800.000000
4    2000.000000
5    1200.000000
6    1300.000000
7    1100.000000
8    1400.000000
9    1500.000000
Name: Area_Acres, dtype: float64

In [ ]:
#  7) fillna median                 ---> robust against outliers

In [16]:
print(df['Yield_Ton_per_Acre'].fillna(df['Yield_Ton_per_Acre'].median()))

0    2.5
1    3.2
2    2.8
3    2.9
4    4.5
5    2.5
6    2.9
7    2.1
8    3.0
9    3.2
Name: Yield_Ton_per_Acre, dtype: float64

In [ ]:
# 8)  fillna mode                    ---> categorical imputation

In [17]:
print(df['Income_INR'].fillna(df['Income_INR'].mode()[0]))

0    5000
1    6200
2    5400
3    7000
4    9000
5    5000
6    5600
7    4800
8    6100
9    6200
Name: Income_INR, dtype: int64

In [ ]:
# 9)  forward fill          ---> uses previous row value (df.fillna(method='ffill') or df.ffill()

In [20]:
# print(df.fillna(method='ffill'))
print(df.ffill())

   Farm_ID       Crop           State  Area_Acres  Yield_Ton_per_Acre  \
0        1       Rice      Tamil Nadu      1200.0                 2.5
1        2      Wheat          Punjab      1500.0                 3.2
2        3      Maize       Karnataka      1500.0                 2.8
3        4     Cotton         Gujarat      1800.0                 2.8
4        5  Sugarcane     Maharashtra      2000.0                 4.5
5        6       Rice      Tamil Nadu      1200.0                 2.5
6        7       Rice  Andhra Pradesh      1300.0                 2.9
7        8     Millet       Rajasthan      1100.0                 2.1
8        9  Groundnut      Tamil Nadu      1400.0                 3.0
9       10      Wheat          Punjab      1500.0                 3.2

  Harvest_Date  Farming_Type Irrigation  Income_INR
0   2026-01-10       Organic        Yes        5000
1   2026-01-11  Conventional         No        6200
2   2026-01-12       Organic        Yes        5400
3   2026-01-13  Conventional         No        7000
4   2026-01-13       Organic        Yes        9000
5   2026-01-10       Organic        Yes        5000
6   2026-01-15       Organic        Yes        5600
7   2026-01-16       Organic         No        4800
8   2026-01-17       Organic         No        6100
9   2026-01-11  Conventional         No        6200

In [ ]:
# 10) backward fill         ---> uses next row value

In [22]:
# print(df.fillna(method='bfill')) 
print(df.bfill())

   Farm_ID       Crop           State  Area_Acres  Yield_Ton_per_Acre  \
0        1       Rice      Tamil Nadu      1200.0                 2.5
1        2      Wheat          Punjab      1500.0                 3.2
2        3      Maize       Karnataka      1800.0                 2.8
3        4     Cotton         Gujarat      1800.0                 4.5
4        5  Sugarcane     Maharashtra      2000.0                 4.5
5        6       Rice      Tamil Nadu      1200.0                 2.5
6        7     Millet  Andhra Pradesh      1300.0                 2.9
7        8     Millet       Rajasthan      1100.0                 2.1
8        9  Groundnut      Tamil Nadu      1400.0                 3.0
9       10      Wheat          Punjab      1500.0                 3.2

  Harvest_Date  Farming_Type Irrigation  Income_INR
0   2026-01-10       Organic        Yes        5000
1   2026-01-11  Conventional         No        6200
2   2026-01-12       Organic        Yes        5400
3   2026-01-13  Conventional         No        7000
4   2026-01-10       Organic        Yes        9000
5   2026-01-10       Organic        Yes        5000
6   2026-01-15       Organic        Yes        5600
7   2026-01-16       Organic         No        4800
8   2026-01-17       Organic         No        6100
9   2026-01-11  Conventional         No        6200

In [ ]:
# 11) replace()              ---> alternative null replacement

In [26]:
print(df.replace(np.nan,'unknown'))

   Farm_ID       Crop           State Area_Acres Yield_Ton_per_Acre  \
0        1       Rice      Tamil Nadu     1200.0                2.5
1        2      Wheat          Punjab     1500.0                3.2
2        3      Maize       Karnataka    unknown                2.8
3        4     Cotton         Gujarat     1800.0            unknown
4        5  Sugarcane     Maharashtra     2000.0                4.5
5        6       Rice      Tamil Nadu     1200.0                2.5
6        7    unknown  Andhra Pradesh     1300.0                2.9
7        8     Millet       Rajasthan     1100.0                2.1
8        9  Groundnut      Tamil Nadu     1400.0                3.0
9       10      Wheat          Punjab     1500.0                3.2

  Harvest_Date  Farming_Type Irrigation  Income_INR
0   2026-01-10       Organic        Yes        5000
1   2026-01-11  Conventional         No        6200
2   2026-01-12       Organic        Yes        5400
3   2026-01-13  Conventional         No        7000
4      unknown       Organic        Yes        9000
5   2026-01-10       Organic        Yes        5000
6   2026-01-15       Organic        Yes        5600
7   2026-01-16       unknown         No        4800
8   2026-01-17       Organic    unknown        6100
9   2026-01-11  Conventional         No        6200

In [ ]:
# 12) detect duplicates     ---> detect duplicate row mask

In [31]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
# 13) count duplicates      ---> number of duplicate rows

In [32]:
print(df.duplicated().sum())

0

In [ ]:
# 14) remove duplicates     ---> removes duplicate rows

In [33]:
print(df.drop_duplicates())

   Farm_ID       Crop           State  Area_Acres  Yield_Ton_per_Acre  \
0        1       Rice      Tamil Nadu      1200.0                 2.5
1        2      Wheat          Punjab      1500.0                 3.2
2        3      Maize       Karnataka         NaN                 2.8
3        4     Cotton         Gujarat      1800.0                 NaN
4        5  Sugarcane     Maharashtra      2000.0                 4.5
5        6       Rice      Tamil Nadu      1200.0                 2.5
6        7        NaN  Andhra Pradesh      1300.0                 2.9
7        8     Millet       Rajasthan      1100.0                 2.1
8        9  Groundnut      Tamil Nadu      1400.0                 3.0
9       10      Wheat          Punjab      1500.0                 3.2

  Harvest_Date  Farming_Type Irrigation  Income_INR
0   2026-01-10       Organic        Yes        5000
1   2026-01-11  Conventional         No        6200
2   2026-01-12       Organic        Yes        5400
3   2026-01-13  Conventional         No        7000
4          NaN       Organic        Yes        9000
5   2026-01-10       Organic        Yes        5000
6   2026-01-15       Organic        Yes        5600
7   2026-01-16           NaN         No        4800
8   2026-01-17       Organic        NaN        6100
9   2026-01-11  Conventional         No        6200

In [ ]:
# 15) data types    ---> shows datatype of every column

In [45]:
df.dtypes

Farm_ID                 int64
Crop                      str
State                     str
Area_Acres            float64
Yield_Ton_per_Acre    float64
Harvest_Date              str
Farming_Type              str
Irrigation                str
Income_INR              int64
dtype: object

In [ ]:
# 16)  convert data type   ---> changes datatype

In [47]:
df['Area_Acres']=df['Area_Acres'].astype(str)
print(df.dtypes)

Farm_ID                 int64
Crop                      str
State                     str
Area_Acres                str
Yield_Ton_per_Acre    float64
Harvest_Date              str
Farming_Type              str
Irrigation                str
Income_INR              int64
dtype: object

In [49]:
df['Farming_Type']=df['Farming_Type'].astype(str)
print(df.dtypes)

Farm_ID                 int64
Crop                      str
State                     str
Area_Acres                str
Yield_Ton_per_Acre    float64
Harvest_Date              str
Farming_Type              str
Irrigation                str
Income_INR              int64
dtype: object

In [ ]:
# 17) info()             ---> shows non-null count and dtypes

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Farm_ID             10 non-null     int64
 1   Crop                9 non-null      str
 2   State               10 non-null     str
 3   Area_Acres          9 non-null      str
 4   Yield_Ton_per_Acre  9 non-null      float64
 5   Harvest_Date        9 non-null      str
 6   Farming_Type        9 non-null      str
 7   Irrigation          9 non-null      str
 8   Income_INR          10 non-null     int64
dtypes: float64(1), int64(2), str(6)
memory usage: 1.2 KB

In [ ]:
# 18) describe()          ---> summary statistics

In [51]:
df.describe()

        Farm_ID  Yield_Ton_per_Acre   Income_INR
count  10.00000            9.000000    10.000000
mean    5.50000            2.966667  6030.000000
std     3.02765            0.678233  1249.044079
min     1.00000            2.100000  4800.000000
25%     3.25000            2.500000  5100.000000
50%     5.50000            2.900000  5850.000000
75%     7.75000            3.200000  6200.000000
max    10.00000            4.500000  9000.000000

In [ ]:
# 19) unique values         ---> returns distinct values

In [53]:
df['State'].unique()

<ArrowStringArray>
[    'Tamil Nadu',         'Punjab',      'Karnataka',        'Gujarat',
    'Maharashtra', 'Andhra Pradesh',      'Rajasthan']
Length: 7, dtype: str

In [ ]:
# 20) count unique       ---> count distinct values

In [56]:
df['Farming_Type'].nunique()

2

In [ ]:
# 21) value counts         ---> frequency of each category

In [55]:
df['Income_INR'].value_counts()

Income_INR
5000    2
6200    2
5400    1
7000    1
9000    1
5600    1
4800    1
6100    1
Name: count, dtype: int64

In [ ]:
# 22) filtering null rows     ---> only rows with null name

In [57]:
df[df['Irrigation'].isnull()]

,Farm_ID,Crop,State,Area_Acres,Yield_Ton_per_Acre,Harvest_Date,Farming_Type,Irrigation,Income_INR
8,9,Groundnut,Tamil Nadu,1400.0,3.0,2026-01-17,Organic,NaN,6100

In [ ]:
# 23) filtering non-null rows      ---> only rows with valid name

In [58]:
df[df['Crop'].notnull()]

,Farm_ID,Crop,State,Area_Acres,Yield_Ton_per_Acre,Harvest_Date,Farming_Type,Irrigation,Income_INR
0,1,Rice,Tamil Nadu,1200.0,2.5,2026-01-10,Organic,Yes,5000
1,2,Wheat,Punjab,1500.0,3.2,2026-01-11,Conventional,No,6200
2,3,Maize,Karnataka,NaN,2.8,2026-01-12,Organic,Yes,5400
3,4,Cotton,Gujarat,1800.0,NaN,2026-01-13,Conventional,No,7000
4,5,Sugarcane,Maharashtra,2000.0,4.5,NaN,Organic,Yes,9000
5,6,Rice,Tamil Nadu,1200.0,2.5,2026-01-10,Organic,Yes,5000
7,8,Millet,Rajasthan,1100.0,2.1,2026-01-16,NaN,No,4800
8,9,Groundnut,Tamil Nadu,1400.0,3.0,2026-01-17,Organic,NaN,6100
9,10,Wheat,Punjab,1500.0,3.2,2026-01-11,Conventional,No,6200

In [ ]:
# 24) sort values           --->  sort dataframe

In [60]:
df.sort_values('Income_INR')

,Farm_ID,Crop,State,Area_Acres,Yield_Ton_per_Acre,Harvest_Date,Farming_Type,Irrigation,Income_INR
7,8,Millet,Rajasthan,1100.0,2.1,2026-01-16,NaN,No,4800
0,1,Rice,Tamil Nadu,1200.0,2.5,2026-01-10,Organic,Yes,5000
5,6,Rice,Tamil Nadu,1200.0,2.5,2026-01-10,Organic,Yes,5000
2,3,Maize,Karnataka,NaN,2.8,2026-01-12,Organic,Yes,5400
6,7,NaN,Andhra Pradesh,1300.0,2.9,2026-01-15,Organic,Yes,5600
8,9,Groundnut,Tamil Nadu,1400.0,3.0,2026-01-17,Organic,NaN,6100
9,10,Wheat,Punjab,1500.0,3.2,2026-01-11,Conventional,No,6200
1,2,Wheat,Punjab,1500.0,3.2,2026-01-11,Conventional,No,6200
3,4,Cotton,Gujarat,1800.0,NaN,2026-01-13,Conventional,No,7000
4,5,Sugarcane,Maharashtra,2000.0,4.5,NaN,Organic,Yes,9000

In [ ]:
# 25) group by             ---> aggregate statistics

In [63]:
df.groupby('State')['Yield_Ton_per_Acre'].mean()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: Average_Of_Yield_Ton_per_Acre, dtype: float64

In [71]:
df['Income_INR_Average'] = df['Income_INR'].mean()

In [72]:
df['Income_INR_Average']

0    6030.0
1    6030.0
2    6030.0
3    6030.0
4    6030.0
5    6030.0
6    6030.0
7    6030.0
8    6030.0
9    6030.0
Name: Income_INR_Average, dtype: float64

In [ ]:
# 26) memory usage         ---> memory consumed by columns

In [73]:
df.memory_usage(deep=True)

Index                            132
Farm_ID                           80
Crop                             135
State                            172
Area_Acres                       136
Yield_Ton_per_Acre                80
Harvest_Date                     172
Farming_Type                     160
Irrigation                       105
Income_INR                        80
Average_Of_Yield_Ton_per_Acre     80
Income_INR_Average                80
dtype: int64