# 1) Data Loading(Available Data)

In [2]:
import pandas as pd

In [58]:
df = pd.read_csv(r"C:\Users\acer\Downloads\diabetes - Copy.csv")

In [59]:
print(df)

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148           72.0           35.0      168  33.6
1            1       85           66.0           29.0      168  26.6
2            8      183           64.0           29.0      168  23.3
3            1       89           66.0           23.0       94  28.1
4            0      137           40.0           35.0      168  43.1
5            5      116           74.0            NaN        0  25.6
6            3       78           50.0           32.0       88  31.0
7           10      115            NaN            0.0        0  35.3
8            2      197           70.0           45.0      543  30.5

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   31        1
1                     0.351   31        1
2                     0.672   32        1
3                     0.167   21        1
4                     2.288   33        1
5                     0.201   30        1
6                     0.248   26        1
7                     0.134   29        1
8                     0.158   53        1

# Data Inspection

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35.0,168,33.6,0.627,31,1
1,1,85,66.0,29.0,168,26.6,0.351,31,1
2,8,183,64.0,29.0,168,23.3,0.672,32,1
3,1,89,66.0,23.0,94,28.1,0.167,21,1
4,0,137,40.0,35.0,168,43.1,2.288,33,1

In [6]:
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35.0,168,33.6,0.627,31,1
1,1,85,66.0,29.0,168,26.6,0.351,31,1
2,8,183,64.0,29.0,168,23.3,0.672,32,1
3,1,89,66.0,23.0,94,28.1,0.167,21,1
4,0,137,40.0,35.0,168,43.1,2.288,33,1
5,5,116,74.0,NaN,0,25.6,0.201,30,1
6,3,78,50.0,32.0,88,31.0,0.248,26,1
7,10,115,NaN,0.0,0,35.3,0.134,29,1
8,2,197,70.0,45.0,543,30.5,0.158,53,1

In [7]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
4,0,137,40.0,35.0,168,43.1,2.288,33,1
5,5,116,74.0,NaN,0,25.6,0.201,30,1
6,3,78,50.0,32.0,88,31.0,0.248,26,1
7,10,115,NaN,0.0,0,35.3,0.134,29,1
8,2,197,70.0,45.0,543,30.5,0.158,53,1

In [8]:
df.tail(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35.0,168,33.6,0.627,31,1
1,1,85,66.0,29.0,168,26.6,0.351,31,1
2,8,183,64.0,29.0,168,23.3,0.672,32,1
3,1,89,66.0,23.0,94,28.1,0.167,21,1
4,0,137,40.0,35.0,168,43.1,2.288,33,1
5,5,116,74.0,NaN,0,25.6,0.201,30,1
6,3,78,50.0,32.0,88,31.0,0.248,26,1
7,10,115,NaN,0.0,0,35.3,0.134,29,1
8,2,197,70.0,45.0,543,30.5,0.158,53,1

In [9]:
df.shape

(9, 9)

In [10]:
df.shape[0]

9

In [11]:
df.shape[1]

9

In [12]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [13]:
df.index

RangeIndex(start=0, stop=9, step=1)

In [14]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure               float64
SkinThickness               float64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               9 non-null      int64
 1   Glucose                   9 non-null      int64
 2   BloodPressure             8 non-null      float64
 3   SkinThickness             8 non-null      float64
 4   Insulin                   9 non-null      int64
 5   BMI                       9 non-null      float64
 6   DiabetesPedigreeFunction  9 non-null      float64
 7   Age                       9 non-null      int64
 8   Outcome                   9 non-null      int64
dtypes: float64(4), int64(5)
memory usage: 780.0 bytes

In [16]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,9.000000,9.000000,8.000000,8.000000,9.000000,9.000000,9.000000,9.000000,9.0
mean,4.000000,127.555556,62.750000,28.500000,155.222222,30.788889,0.538444,31.777778,1.0
std,3.464102,42.497386,11.756457,13.158376,161.043300,5.997175,0.686137,8.757536,0.0
min,0.000000,78.000000,40.000000,0.000000,0.000000,23.300000,0.134000,21.000000,1.0
25%,1.000000,89.000000,60.500000,27.500000,88.000000,26.600000,0.167000,29.000000,1.0
50%,3.000000,116.000000,66.000000,30.500000,168.000000,30.500000,0.248000,31.000000,1.0
75%,6.000000,148.000000,70.500000,35.000000,168.000000,33.600000,0.627000,32.000000,1.0
max,10.000000,197.000000,74.000000,45.000000,543.000000,43.100000,2.288000,53.000000,1.0

In [61]:
df.sample(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
5,5,116,74.0,NaN,0,25.6,0.201,30,1
8,2,197,70.0,45.0,543,30.5,0.158,53,1
1,1,85,66.0,29.0,168,26.6,0.351,31,1

In [17]:
print(df.size)

81

In [18]:
print(len(df))

9

In [19]:
print(df['Pregnancies'])

0     6
1     1
2     8
3     1
4     0
5     5
6     3
7    10
8     2
Name: Pregnancies, dtype: int64

In [20]:
print(df[['BloodPressure','Insulin']])

   BloodPressure  Insulin
0           72.0      168
1           66.0      168
2           64.0      168
3           66.0       94
4           40.0      168
5           74.0        0
6           50.0       88
7            NaN        0
8           70.0      543

In [21]:
print(df.loc[0])

Pregnancies                   6.000
Glucose                     148.000
BloodPressure                72.000
SkinThickness                35.000
Insulin                     168.000
BMI                          33.600
DiabetesPedigreeFunction      0.627
Age                          31.000
Outcome                       1.000
Name: 0, dtype: float64

In [22]:
print(df.loc[1])

Pregnancies                   1.000
Glucose                      85.000
BloodPressure                66.000
SkinThickness                29.000
Insulin                     168.000
BMI                          26.600
DiabetesPedigreeFunction      0.351
Age                          31.000
Outcome                       1.000
Name: 1, dtype: float64

In [23]:
print(df.iloc[5])

Pregnancies                   5.000
Glucose                     116.000
BloodPressure                74.000
SkinThickness                   NaN
Insulin                       0.000
BMI                          25.600
DiabetesPedigreeFunction      0.201
Age                          30.000
Outcome                       1.000
Name: 5, dtype: float64

In [24]:
print(df)

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148           72.0           35.0      168  33.6
1            1       85           66.0           29.0      168  26.6
2            8      183           64.0           29.0      168  23.3
3            1       89           66.0           23.0       94  28.1
4            0      137           40.0           35.0      168  43.1
5            5      116           74.0            NaN        0  25.6
6            3       78           50.0           32.0       88  31.0
7           10      115            NaN            0.0        0  35.3
8            2      197           70.0           45.0      543  30.5

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   31        1
1                     0.351   31        1
2                     0.672   32        1
3                     0.167   21        1
4                     2.288   33        1
5                     0.201   30        1
6                     0.248   26        1
7                     0.134   29        1
8                     0.158   53        1

In [25]:
print(df.loc[0,'Pregnancies'])

6

In [26]:
print(df.loc[2:5,['Pregnancies','Glucose']])

   Pregnancies  Glucose
2            8      183
3            1       89
4            0      137
5            5      116

In [27]:
print(df.loc[5:8,['Insulin','Age']])

   Insulin  Age
5        0   30
6       88   26
7        0   29
8      543   53

In [28]:
print(df.loc[df['Glucose']>100,['Glucose','Pregnancies']])

   Glucose  Pregnancies
0      148            6
2      183            8
4      137            0
5      116            5
7      115           10
8      197            2

In [29]:
print(df.loc[df['Pregnancies']<=10,['Pregnancies']])

   Pregnancies
0            6
1            1
2            8
3            1
4            0
5            5
6            3
7           10
8            2

# 2) Data Loading (Created data)

In [98]:
data = {
    "Player": ["Virat", "Rohit", "Gill", "Rahul", "Hardik"],
    "Matches": [120, 150, None, 75, 95],
    "Runs": [5600, 6200, 1800, 3100, None],
    "Average": [55.2, 49.8, 47.5, None, 39.4],
    "Country": ["None", "India", "India", "India", "India"],
    "Winning_Matches":[2,5,4,3,5]
}

df = pd.DataFrame(data)

In [99]:
print(df)

   Player  Matches    Runs  Average Country  Winning_Matches
0   Virat    120.0  5600.0     55.2    None                2
1   Rohit    150.0  6200.0     49.8   India                5
2    Gill      NaN  1800.0     47.5   India                4
3   Rahul     75.0  3100.0      NaN   India                3
4  Hardik     95.0     NaN     39.4   India                5

# Data Inspection

In [100]:
df.head()

   Player  Matches    Runs  Average Country  Winning_Matches
0   Virat    120.0  5600.0     55.2    None                2
1   Rohit    150.0  6200.0     49.8   India                5
2    Gill      NaN  1800.0     47.5   India                4
3   Rahul     75.0  3100.0      NaN   India                3
4  Hardik     95.0     NaN     39.4   India                5

In [101]:
df.tail()

   Player  Matches    Runs  Average Country  Winning_Matches
0   Virat    120.0  5600.0     55.2    None                2
1   Rohit    150.0  6200.0     49.8   India                5
2    Gill      NaN  1800.0     47.5   India                4
3   Rahul     75.0  3100.0      NaN   India                3
4  Hardik     95.0     NaN     39.4   India                5

In [102]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Player           5 non-null      str
 1   Matches          4 non-null      float64
 2   Runs             4 non-null      float64
 3   Average          4 non-null      float64
 4   Country          5 non-null      str
 5   Winning_Matches  5 non-null      int64
dtypes: float64(3), int64(1), str(2)
memory usage: 421.0 bytes

In [103]:
df.describe()

          Matches         Runs    Average  Winning_Matches
count    4.000000     4.000000   4.000000          5.00000
mean   110.000000  4175.000000  47.975000          3.80000
std     32.403703  2075.853238   6.564742          1.30384
min     75.000000  1800.000000  39.400000          2.00000
25%     90.000000  2775.000000  45.475000          3.00000
50%    107.500000  4350.000000  48.650000          4.00000
75%    127.500000  5750.000000  51.150000          5.00000
max    150.000000  6200.000000  55.200000          5.00000

In [104]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [105]:
df.dtypes

Player                 str
Matches            float64
Runs               float64
Average            float64
Country                str
Winning_Matches      int64
dtype: object

In [106]:
df.columns

Index(['Player', 'Matches', 'Runs', 'Average', 'Country', 'Winning_Matches'], dtype='str')

In [107]:
df.shape

(5, 6)

In [108]:
df.shape[0]

5

In [109]:
df.shape[1]

6

In [110]:
df.sample(2)

  Player  Matches    Runs  Average Country  Winning_Matches
1  Rohit    150.0  6200.0     49.8   India                5
2   Gill      NaN  1800.0     47.5   India                4

In [111]:
df.size

30

In [112]:
print(len(df))

5

In [113]:
print(df.loc[0])

Player              Virat
Matches             120.0
Runs               5600.0
Average              55.2
Country              None
Winning_Matches         2
Name: 0, dtype: object

In [114]:
print(df.loc[1])

Player              Rohit
Matches             150.0
Runs               6200.0
Average              49.8
Country             India
Winning_Matches         5
Name: 1, dtype: object

In [115]:
print(df.iloc[4])

Player             Hardik
Matches              95.0
Runs                  NaN
Average              39.4
Country             India
Winning_Matches         5
Name: 4, dtype: object

In [116]:
print(df['Player'])

0     Virat
1     Rohit
2      Gill
3     Rahul
4    Hardik
Name: Player, dtype: str

In [118]:
print(df[['Player','Runs','Winning_Matches']])

   Player    Runs  Winning_Matches
0   Virat  5600.0                2
1   Rohit  6200.0                5
2    Gill  1800.0                4
3   Rahul  3100.0                3
4  Hardik     NaN                5

In [120]:
print(df)

   Player  Matches    Runs  Average Country  Winning_Matches
0   Virat    120.0  5600.0     55.2    None                2
1   Rohit    150.0  6200.0     49.8   India                5
2    Gill      NaN  1800.0     47.5   India                4
3   Rahul     75.0  3100.0      NaN   India                3
4  Hardik     95.0     NaN     39.4   India                5

In [121]:
print(df.loc[0,'Matches'])

120.0

In [122]:
print(df.loc[1:3,['Matches','Winning_Matches']])

   Matches  Winning_Matches
1    150.0                5
2      NaN                4
3     75.0                3

In [124]:
print(df.loc[df['Winning_Matches']<3,['Winning_Matches','Runs']])

   Winning_Matches    Runs
0                2  5600.0

In [126]:
print(df.loc[df['Runs']>=3000,['Runs','Player']])

     Runs Player
0  5600.0  Virat
1  6200.0  Rohit
3  3100.0  Rahul

In [128]:
print(df.loc[df['Country'] == 'India',['Player']])

   Player
1   Rohit
2    Gill
3   Rahul
4  Hardik