# (TASK-4) -----> Statistics And Pandas Functions

In [ ]:
# -----> TO FIND STANDARD DEVIATION AND VARIANCE USING PYTHON <-----

In [10]:
import pandas as pd

In [11]:
x = [12,28,35,49,56,63,82,97,74]

In [12]:
mean = sum(x) / len(x)

In [13]:
numerator = 0 
for i in x:
    numerator += (i-mean) ** 2

In [14]:
denominator = len(x)

In [15]:
variance = numerator/denominator

In [16]:
standard_deviation = variance ** 0.5

In [17]:
print("MEAN =", mean) 
print("NUMERATOR =", numerator) 
print("DENOMINATOR =", denominator) 
print("VARIANCE =", variance)
print("STANDARD DEVIATION =", standard_deviation)

MEAN = 55.111111111111114
NUMERATOR = 5932.888888888889
DENOMINATOR = 9
VARIANCE = 659.2098765432098
STANDARD DEVIATION = 25.675082795255204

# STATISTICS

In [ ]:
# 1) MEAN

In [201]:
import numpy as np

In [213]:
x = np.array([10,20,30,40,50,85,100,155,184,222])
print(x)

[ 10  20  30  40  50  85 100 155 184 222]

In [214]:
print(np.mean(x))

89.6

In [ ]:
# 2) MEDIAN

In [207]:
x = np.array([10,20,30,40,50,75,100,111])

In [208]:
print(np.median(x))

45.0

In [ ]:
# 3) MODE

In [30]:
x = np.array([22,30,4,22,5,6,5,7,3,2,3,45,7,9,3,7,5])

In [31]:
values,counts = np.unique(x,return_counts=True)

In [32]:
mode = values[np.argmax(counts)]

In [33]:
print("mode:",mode)

mode: 3

In [ ]:
# 4) STANDARD DEVIATION

In [34]:
x = np.array([10,20,30,40,50,75,100,111])

In [35]:
print(np.std(x))

34.792240514229604

In [ ]:
# 5) VARIANCE

In [41]:
x = np.array([10,20,30,40,50,75,100,111])

In [42]:
print(np.var(x))

1210.5

In [ ]:
# 5) PERCENTILES

In [47]:
x = np.array([10,24,36,48,50,100,126,134])

In [52]:
print(np.percentile(x,5))
print(np.percentile(x,25))
print(np.percentile(x,50))
print(np.percentile(x,75))
print(np.percentile(x,100))

14.9
33.0
49.0
106.5
134.0

In [ ]:
# 6) QUARTILES

In [53]:
x = np.array([10,24,36,48,50,100,126,134])

In [56]:
Q1 = np.percentile(x,25)
Q2 = np.percentile(x,50)
Q3 = np.percentile(x,75)

In [57]:
print(Q1)
print(Q2)
print(Q3)

33.0
49.0
106.5

In [ ]:
# 7) INTER QUARTILE RANGE(IQR)

In [63]:
x = np.array([10,24,36,48,50,100,126,134])

In [64]:
Q1 = np.percentile(x,25)
Q3 = np.percentile(x,75) 

print(Q1)
print(Q3)

33.0
106.5

In [65]:
IQR = Q3-Q1
print(IQR)

73.5

In [ ]:
# 8) OUTLIER DETECTION(IQR METHOD)

In [95]:
x = np.array([5,10,15,20,25,30,35,40,45,50,55,70,65,60,75,80,85,90,95,100])

In [99]:
Q1 = np.percentile(x,25)
Q3 = np.percentile(x,75)

IQR = Q3-Q1 

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR 

outliers = x[(x < lower) | (x > upper)]

In [100]:
print("Q1:" , Q1)
print("Q3:" , Q3) 
print("IQR:" , IQR)
print("LOWER:" , lower )
print("UPPER:" , upper)
print("OUTLIERS:" , outliers)

Q1: 28.75
Q3: 76.25
IQR: 47.5
LOWER: -42.5
UPPER: 147.5
OUTLIERS: []

In [ ]:
# 9) MINIMUM

In [77]:
x = np.array([5,10,20,30,40,50])

In [78]:
print(np.min(x))

5

In [79]:
# 10) MAXIMUM

In [80]:
x = np.array([10,20,30,40,50,100])

In [81]:
print(np.max(x))

100

In [ ]:
# 11) RANGE

In [85]:
x = np.array([5,10,20,30,40,50,100])

In [86]:
range1 = np.max(x) - np.min(x)

In [87]:
print("range:",range1)

range: 95

In [ ]:
# 12) SUM

In [88]:
x = np.array([10,20,30,40,50])

In [89]:
print(np.sum(x))

150

In [ ]:
# 13) COUNT

In [90]:
x = np.array([5,10,20,30,40,50,100])

In [91]:
print(x.size)

7

In [ ]:
# 14) AVERAGE

In [93]:
x = np.array([5,10,20,30,40,50,100])

In [94]:
print(np.average(x))

36.42857142857143

In [101]:
import pandas as pd
import numpy as np

In [104]:
# Sample data
data = [12, 15, 18, 20, 22, 25, 30, 35, 40, 100]

In [105]:
df = pd.DataFrame(data, columns=["Marks"])

In [106]:
print(df)

   Marks
0     12
1     15
2     18
3     20
4     22
5     25
6     30
7     35
8     40
9    100

In [107]:
# Mean
print("Mean:", df["Marks"].mean())

Mean: 31.7

In [108]:
# Median
print("Median:", df["Marks"].median())

Median: 23.5

In [109]:
# Mode
print("Mode:")
print(df["Marks"].mode())

Mode:
0     12
1     15
2     18
3     20
4     22
5     25
6     30
7     35
8     40
9    100
Name: Marks, dtype: int64

In [110]:
# Minimum
print("Minimum:", df["Marks"].min())

Minimum: 12

In [111]:
# Maximum
print("Maximum:", df["Marks"].max())

Maximum: 100

In [112]:
# Sum
print("Sum:", df["Marks"].sum())

Sum: 317

In [113]:
# Count
print("Count:", df["Marks"].count())

Count: 10

In [114]:
# Range
print("Range:", df["Marks"].max() - df["Marks"].min())

Range: 88

In [115]:
# Variance
print("Variance:", df["Marks"].var())

Variance: 653.1222222222221

In [116]:
# Standard Deviation
print("Standard Deviation:", df["Marks"].std())

Standard Deviation: 25.55625602904741

In [117]:
# Percentiles
print("25th Percentile:", df["Marks"].quantile(0.25))
print("50th Percentile:", df["Marks"].quantile(0.50))
print("75th Percentile:", df["Marks"].quantile(0.75))

25th Percentile: 18.5
50th Percentile: 23.5
75th Percentile: 33.75

In [118]:
# Quartiles
Q1 = df["Marks"].quantile(0.25)
Q2 = df["Marks"].quantile(0.50)
Q3 = df["Marks"].quantile(0.75)

print("Q1:", Q1)
print("Q2:", Q2)
print("Q3:", Q3)

Q1: 18.5
Q2: 23.5
Q3: 33.75

In [120]:
# Interquartile Range (IQR) 
Q1 = df["Marks"].quantile(0.25)
Q2 = df["Marks"].quantile(0.50)
Q3 = df["Marks"].quantile(0.75)

print("Q1:", Q1)
print("Q2:", Q2)
print("Q3:", Q3)

IQR = Q3 - Q1
print("IQR:", IQR)

Q1: 18.5
Q2: 23.5
Q3: 33.75
IQR: 15.25

In [ ]:
# Outlier Detection
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

outliers = df[(df["Marks"] < lower_limit) | (df["Marks"] > upper_limit)]
print("Outliers:",outliers)

# PANDAS FUNCTIONS

In [128]:
import pandas as pd

In [129]:
data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 25, 30]
}

df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   25
2    C   30

In [130]:
# 1) RENAME COLUMNS

In [131]:
df.rename(columns = {"Age":"Student_Age"},inplace = True)

In [132]:
print(df)

  Name  Student_Age
0    A           20
1    B           25
2    C           30

In [133]:
# 2) ADD NEW COLUMNS

In [134]:
df["Marks"] = [80,90,85]

df["Marks"]

In [135]:
print(df)

  Name  Student_Age  Marks
0    A           20     80
1    B           25     90
2    C           30     85

In [ ]:
# 3) DELETE COLUMN

In [136]:
df.drop("Marks",axis=1)

  Name  Student_Age
0    A           20
1    B           25
2    C           30

In [ ]:
# 4) CONCAT

In [156]:
df1 = pd.DataFrame({
    "Id":[1,2,3],
    "Name":["A","B","C"]
})
df2 = pd.DataFrame({
    "Id":[4,5,6],
    "Name":["D","E","F"]
})

In [157]:
print(df1)

   Id Name
0   1    A
1   2    B
2   3    C

In [158]:
print(df2)

   Id Name
0   4    D
1   5    E
2   6    F

In [159]:
pd.concat([df1,df2])

   Id Name
0   1    A
1   2    B
2   3    C
0   4    D
1   5    E
2   6    F

In [ ]:
# 5) MERGE

In [160]:
student = pd.DataFrame({
    "Id":[1,2,3],
    "Name":["anbu","Bala","Chinnu"]
})
marks = pd.DataFrame({
    "Id":[1,2,3],
    "Marks":[80,90,88]
})

In [161]:
pd.merge(student,marks, on="Id")

   Id    Name  Marks
0   1    anbu     80
1   2    Bala     90
2   3  Chinnu     88

In [ ]:
# 6) APPLY() WITH LAMBDA

In [162]:
df = pd.DataFrame({"Marks": [80,90,70]})

df["Bonus"] = df["Marks"].apply(lambda x: x+5)
print(df)

   Marks  Bonus
0     80     85
1     90     95
2     70     75

In [ ]:
# 7) SET_INDEX()

In [178]:
df = pd.DataFrame({
    "Id": [101,102,103],
    "Name": ["Ram","Sam","John"],
    "Marks": [85,90,88]
})
print(df)

    Id  Name  Marks
0  101   Ram     85
1  102   Sam     90
2  103  John     88

In [179]:
df.set_index("Id")

     Name  Marks
Id
101   Ram     85
102   Sam     90
103  John     88

In [ ]:
# 8) RESET_INDEX()

In [180]:
df.reset_index()

   index   Id  Name  Marks
0      0  101   Ram     85
1      1  102   Sam     90
2      2  103  John     88

In [ ]:
# 9) CORRELATION

In [187]:
df = pd.DataFrame({
    "Math": [50,60,70,80,90],
    "Science": [55,65,75,85,95]
}) 

print(df)

   Math  Science
0    50       55
1    60       65
2    70       75
3    80       85
4    90       95

In [188]:
df.corr()

         Math  Science
Math      1.0      1.0
Science   1.0      1.0

In [189]:
df = pd.DataFrame({
    "Math": [50,60,70,80,90],
    "Science": [52,63,74,86,97]
}) 

print(df)

   Math  Science
0    50       52
1    60       63
2    70       74
3    80       86
4    90       97

In [190]:
df.corr()

             Math   Science
Math     1.000000  0.999883
Science  0.999883  1.000000

In [191]:
df.corr(numeric_only = True)

             Math   Science
Math     1.000000  0.999883
Science  0.999883  1.000000

In [184]:
# 10) COVARIANCE()

In [192]:
df = pd.DataFrame({
    "Math": [50,60,70,80,90],
    "Science": [55,65,75,85,95]
}) 

print(df)

   Math  Science
0    50       55
1    60       65
2    70       75
3    80       85
4    90       95

In [193]:
df.cov()

          Math  Science
Math     250.0    250.0
Science  250.0    250.0

In [195]:
df = pd.DataFrame({
    "Math": [50,60,70,80,90],
    "Science": [52,63,74,86,97]
}) 

print(df)

   Math  Science
0    50       52
1    60       63
2    70       74
3    80       86
4    90       97

In [196]:
df.cov()

          Math  Science
Math     250.0    282.5
Science  282.5    319.3

In [197]:
df.cov(numeric_only = True)

          Math  Science
Math     250.0    282.5
Science  282.5    319.3

In [ ]:
# 11) QUANTILE()

In [198]:
df = pd.DataFrame({
    "Marks": [50,60,70,80,90]
})
print(df)

   Marks
0     50
1     60
2     70
3     80
4     90

In [199]:
df["Marks"].quantile(0.25)

np.float64(60.0)